<?php $this->layoutHelper()->setPageTitle('Gestión de Listas'); ?>
<?php
  $this->notyFlash(true);
?>
<div class="card">
  <div class="card-header card-header-icon" data-background-color="rose">
      <i class="material-icons">assignment</i>
  </div>
  <div class="card-content">
    <?= $this->renderForm($this->form) ?>
  </div>
</div>

<script>
    $(document).ready(function () {
        $(".is-fileinput").prepend('<a href="/distributionList.csv">Descargar Ejemplo - Lista de distribución</a>');
        $(".is-fileinput").append('<label id="fileNameSelected"></label>');
        $("#fileUpload").change(function () {
            var name = this.value.split("\\").pop();
            if(name !== ""){
                $("#fileNameSelected").html(name);
            }
        });
    });
</script>
